version: "3.4"
services:
  app:
    build:
      context: .
      dockerfile: infrastructure/docker/java.dockerfile
      target: dev
    volumes:
      - ./:/code
    working_dir: /code
    command: ["mvn test spring-boot:run"]
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_ADDR: ${SERVER_ADDR}
      SERVER_PORT: ${SERVER_PORT}
      APP_DEBUG: ${APP_DEBUG}
    tty: true
    ports:
      - "8999:8081"
  postgres:
    image: "postgres:11-alpine"
    environment:
      POSTGRES_DB: epaper
      POSTGRES_USER: epaper
      POSTGRES_PASSWORD: password
    ports:
      - "5555:5432"
