name: CI

on: push


jobs:
  test_java_api:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        run: mvn -B -U clean test
  
  
  test_python_tunnel_proxy:
    runs-on: ubuntu-20.04
    env:
       API_URL: "https://api.epaper.opendatahub.testingmachine.eu"
      WS_URL: "ws://localhost/ws"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |
          cd proxy
          echo "API_URL=${API_URL}" > .env
          touch local-tunnel.log
          timeout -s SIGKILL 5 python3 proxy.py || test "137" = "$?"
      
  test_python_websocket_proxy:
    runs-on: ubuntu-20.04
    env:
      API_URL: "https://api.epaper.opendatahub.testingmachine.eu"
      WS_URL: "ws://localhost/ws"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |
          cd websocket-proxy
          echo "API_URL=$API_URL" > .env
          echo "WS_URL=$WS_URL" >> .env
          timeout -s SIGKILL 5 python3 websocket-proxy.py || test "137" = "$?"
